version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app_${SPRING_PROFILES_ACTIVE:-dev}
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d:ro
      - ${DB_VOLUME:-/var/lib/postgresql/data}  #prod/persistent = $env:DB_VOLUME="dbdata:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 40
      start_period: 40s

  config-server:
    build:
      context: ../config-server
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8089/actuator/health"]
      interval: "5s"
      timeout: "3s"
      retries: 30
  eureka-server:
    build:
      context: ../eureka-server
      dockerfile: Dockerfile
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: eureka-server
      SPRING_PROFILES_ACTIVE: dev
      #SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8089"
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
      SERVER_PORT: "8070"
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_CONFIG: DEBUG
    ports:
      - "8070:8070"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8070/actuator/health"]
      interval: "5s"
      timeout: "3s"
      retries: 30

  library-service:
    build:
      context: ../library-service
      dockerfile: Dockerfile
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: library-service
      SPRING_PROFILES_ACTIVE: dev
      #SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8089"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8070/eureka/"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/app_dev"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "pass"
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=60 -XX:InitialRAMPercentage=60 -XX:+UseContainerSupport"
    deploy:
      resources:
        limits:
          memory: 768m
    ports:
      - "8081:8080"

  stock-service:
    build:
      context: ../stock-service
      dockerfile: Dockerfile
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: stock-service
      SPRING_PROFILES_ACTIVE: dev
      #SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8089"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8070/eureka/"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/app_dev"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "pass"
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=60 -XX:InitialRAMPercentage=60 -XX:+UseContainerSupport"
    deploy:
      resources:
        limits:
          memory: 768m
    ports:
      - "8082:8080"

volumes:
  dbdata:


